### ISSUE TITLE
You break the compatibility of fxp/composer-asset-plugin

### ISSUE THREAD

**Issue by francoispluchino** [yidas/yii2-composer-bower-skip#1]
@yidas,

With your workaround of the plugin [Fxp Composer Asset Plugin](https://github.com/fxpio/composer-asset-plugin) on Packagist using the `provide`, you break the compatibility of the plugin.

Indeed, Composer first check packages on Packagist, and uses the VCS Repositories after. Now that you reference packages under the virtual vendor `bower-asset` in Packagist, Composer considers that the package exists on Packagist.

Please remove your Packagist references.

For more details, see fxpio/composer-asset-plugin#268 and cebe/assetfree-yii2#4.

Best regards

**Comment by SilverFire** [comment]
Related: https://github.com/composer/packagist/issues/756

**Comment by francoispluchino** [comment]
@SilverFire Yes, it's another package, not visible on Packagist that is problematic, I close this issue.

**Comment by yidas** [comment]
Thanks!
